
project_id = "dfnrhiovacznpnzevzfe"

[functions.admin-operations]
verify_jwt = false

[functions.fetch-book-details]
verify_jwt = false

[functions.generate-embeddings]
verify_jwt = false

[functions.generate-search-embedding]
verify_jwt = false
