
-- Insert sample blog posts
INSERT INTO blog_posts (id, title, excerpt, content, date, readtime, author, category, tags, image) VALUES
('ai-cybersecurity-2024', 'The Future of AI in Cybersecurity: 2024 Trends and Predictions', 'Exploring how artificial intelligence is revolutionizing cybersecurity defenses and what organizations need to know for 2024.', 'Artificial intelligence is transforming the cybersecurity landscape at an unprecedented pace. As we move through 2024, organizations must understand how AI-powered threats and defenses are reshaping the security paradigm...\n\nKey trends include automated threat detection, predictive analytics for vulnerability assessment, and AI-driven incident response systems. However, with these advances come new challenges, including adversarial AI attacks and the need for AI governance frameworks.\n\nOrganizations should focus on:\n\n1. Implementing AI-enhanced SIEM systems\n2. Developing AI literacy among security teams\n3. Creating robust AI governance policies\n4. Investing in explainable AI for security decisions\n\nThe future belongs to those who can effectively balance AI innovation with security best practices.', '2024-01-15', '8 min read', 'Dr. Troy Williams', 'AI & Technology', ARRAY['AI', 'cybersecurity', 'trends', '2024'], 'https://images.unsplash.com/photo-1555255707-c07966088b7b'),

('stolen-nation-insights', 'Digital Sovereignty: Lessons from "Stolen Nation"', 'Key insights from my latest book on protecting American digital infrastructure and maintaining technological independence.', 'In "Stolen Nation," I explore the critical threats facing America''s digital sovereignty and the urgent need for comprehensive cybersecurity reforms...\n\nThe book reveals how foreign adversaries are systematically targeting our critical infrastructure, from power grids to financial systems. The evidence is clear: we are in a digital cold war, and the stakes have never been higher.\n\nKey themes include:\n\n- The vulnerability of our supply chain to foreign influence\n- The need for domestic semiconductor manufacturing\n- Protecting intellectual property from state-sponsored theft\n- Building resilient communication networks\n\nEvery American leader, from corporate executives to government officials, must understand these threats and take action to protect our nation''s digital future.', '2024-01-10', '12 min read', 'Dr. Troy Williams', 'National Security', ARRAY['digital sovereignty', 'national security', 'book', 'infrastructure'], 'https://images.unsplash.com/photo-1451187580459-43490279c0fa'),

('fraud-prevention-strategies', 'Advanced Fraud Prevention: Beyond Traditional Methods', 'Modern fraud requires modern solutions. Here''s how organizations can stay ahead of evolving threats.', 'Traditional fraud prevention methods are no longer sufficient in today''s digital landscape. Fraudsters are using AI, deepfakes, and sophisticated social engineering to bypass conventional security measures...\n\nEffective fraud prevention now requires:\n\n1. **Behavioral Analytics**: Understanding normal user patterns to detect anomalies\n2. **Real-time Risk Assessment**: Evaluating transactions as they occur\n3. **Multi-factor Authentication**: Layered security approaches\n4. **AI-powered Detection**: Machine learning models that adapt to new threats\n5. **Cross-channel Monitoring**: Tracking activities across all touchpoints\n\nOrganizations must also invest in employee training and incident response capabilities. The human element remains both the weakest link and the strongest defense in fraud prevention.', '2024-01-05', '10 min read', 'Dr. Troy Williams', 'Fraud Prevention', ARRAY['fraud prevention', 'security', 'analytics', 'AI'], 'https://images.unsplash.com/photo-1563013544-824ae1b704d3'),

('cybersecurity-policy-2024', 'Cybersecurity Policy Reform: What America Needs Now', 'An analysis of current policy gaps and recommendations for strengthening America''s cybersecurity posture.', 'America''s cybersecurity policy framework requires immediate and comprehensive reform. Current regulations are fragmented, outdated, and insufficient to address modern threats...\n\nCritical policy areas needing attention:\n\n**1. Critical Infrastructure Protection**\n- Mandatory security standards for utilities\n- Regular penetration testing requirements\n- Incident reporting within 24 hours\n\n**2. Supply Chain Security**\n- Vendor risk assessment protocols\n- Domestic sourcing requirements for critical components\n- Third-party security validation\n\n**3. Data Protection**\n- Federal privacy legislation similar to GDPR\n- Data breach notification requirements\n- Consumer rights to data deletion\n\n**4. International Cooperation**\n- Bilateral cybersecurity agreements\n- Threat intelligence sharing protocols\n- Joint response capabilities\n\nThe time for incremental change has passed. We need bold, comprehensive action to secure America''s digital future.', '2023-12-28', '15 min read', 'Dr. Troy Williams', 'Policy & Governance', ARRAY['policy', 'governance', 'cybersecurity', 'regulation'], 'https://images.unsplash.com/photo-1589994965851-a8f479c573a9'),

('ai-ethics-security', 'AI Ethics in Cybersecurity: Balancing Innovation and Responsibility', 'Exploring the ethical considerations when deploying AI in cybersecurity applications.', 'As AI becomes central to cybersecurity operations, we must address the ethical implications of automated decision-making in security contexts...\n\nKey ethical considerations include:\n\n**Bias and Fairness**\n- Ensuring AI systems don''t discriminate against certain groups\n- Regular auditing of AI decision patterns\n- Diverse training data to prevent algorithmic bias\n\n**Transparency and Explainability**\n- Understanding how AI reaches security decisions\n- Providing clear justifications for automated actions\n- Maintaining human oversight in critical decisions\n\n**Privacy and Surveillance**\n- Balancing security needs with individual privacy\n- Implementing data minimization principles\n- Establishing clear boundaries for AI monitoring\n\n**Accountability**\n- Defining responsibility for AI-driven security incidents\n- Establishing liability frameworks\n- Creating audit trails for AI decisions\n\nThe cybersecurity community must lead by example in responsible AI deployment, ensuring that our tools protect not just our systems, but our values as well.', '2023-12-20', '11 min read', 'Dr. Troy Williams', 'AI & Technology', ARRAY['AI ethics', 'cybersecurity', 'responsible AI', 'governance'], 'https://images.unsplash.com/photo-1677442136019-21780ecad995');

-- Insert sample webinars
INSERT INTO webinars (title, description, date, duration_minutes, max_attendees, is_public) VALUES
('AI-Powered Cybersecurity: Implementation Strategies', 'Join Dr. Troy Williams for an in-depth discussion on implementing AI-powered cybersecurity solutions in your organization. Learn practical strategies, common pitfalls, and best practices.', '2024-07-15 14:00:00+00', 90, 100, true),
('Digital Sovereignty and National Security', 'An executive briefing on protecting critical infrastructure and maintaining technological independence in an interconnected world.', '2024-07-22 15:00:00+00', 60, 50, true),
('Advanced Fraud Detection Techniques', 'Explore cutting-edge fraud detection methods using behavioral analytics, machine learning, and real-time risk assessment.', '2024-07-29 13:00:00+00', 75, 75, true),
('Cybersecurity Policy and Governance', 'Understanding the regulatory landscape and building effective cybersecurity governance frameworks for modern organizations.', '2024-08-05 14:00:00+00', 60, 60, true);

-- Insert sample testimonials
INSERT INTO testimonials (name, email, title, organization, testimonial, rating, category, is_approved) VALUES
('Sarah Chen', 'sarah.chen@nsi.gov', 'Director of AI Research', 'National Security Institute', 'Dr. Williams'' insights on AI security frameworks are groundbreaking. His work is defining the future of safe AI for critical infrastructure.', 5, 'cybersecurity', true),
('Robert Keller', 'r.keller@defense.gov', 'Former Intelligence Officer', 'U.S. Department of Defense', 'Stolen Nation is a wake-up call that every American should read. Troy Williams illuminates threats to our digital sovereignty with clarity and urgency.', 5, 'consulting', true),
('Michelle Dawson', 'mdawson@ameritech.com', 'Chief Information Security Officer', 'AmeriTech Solutions', 'Troy''s approach to cybersecurity doesn''t just solve today''s problems—it anticipates tomorrow''s threats. His Proactive Prevention Platform has revolutionized how we think about digital defense.', 5, 'consulting', true),
('James Harrison', 'jharrison@senate.gov', 'Technology Policy Advisor', 'Senate Commerce Committee', 'Few people truly understand the intersection of AI and national security like Dr. Williams. His work bridges the gap between theoretical advancement and practical defense strategies.', 5, 'policy', true),
('Lisa Rodriguez', 'lrodriguez@cybercorp.com', 'VP of Security Operations', 'CyberCorp International', 'Dr. Williams'' webinar on AI-powered threat detection transformed our security operations. His practical insights helped us reduce false positives by 60% while improving threat detection accuracy.', 5, 'training', true),
('David Kim', 'dkim@financeplus.com', 'Chief Risk Officer', 'FinancePlus Bank', 'The fraud prevention strategies Dr. Williams shared saved our organization millions. His expertise in behavioral analytics is unmatched in the industry.', 5, 'fraud-prevention', true),
('Amanda Foster', 'afoster@techstart.com', 'CEO', 'TechStart Innovations', 'As a startup in the cybersecurity space, Dr. Williams'' mentorship was invaluable. His guidance helped us navigate complex regulatory requirements and build a robust security framework.', 5, 'mentoring', true),
('Colonel Michael Brooks', 'mbrooks@usarmy.mil', 'Cybersecurity Division Chief', 'U.S. Army Cyber Command', 'Dr. Williams'' expertise in digital warfare and cyber defense is exceptional. His strategic insights have been instrumental in strengthening our nation''s cyber capabilities.', 5, 'consulting', true);

-- Insert contact messages for demonstration
INSERT INTO contact_messages (name, email, subject, message) VALUES
('John Anderson', 'john.anderson@techcorp.com', 'Cybersecurity Consultation Request', 'We are a Fortune 500 company looking to enhance our cybersecurity posture. We would like to discuss potential consulting opportunities with Dr. Williams.'),
('Maria Gonzalez', 'maria.g@university.edu', 'Research Collaboration', 'I am a professor of computer science interested in collaborating on AI ethics research. Would Dr. Williams be available for a discussion about potential joint research projects?'),
('Steve Wilson', 'swilson@gov.agency.gov', 'Speaking Engagement', 'We are organizing a cybersecurity summit for government agencies and would like to invite Dr. Williams as a keynote speaker. Please let us know his availability.'),
('Jennifer Lee', 'jennifer.lee@startup.com', 'Mentoring Program', 'Our cybersecurity startup is in early stages and we would benefit greatly from Dr. Williams'' mentorship. How can we apply for the mentoring program?');
