// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dfnrhiovacznpnzevzfe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRmbnJoaW92YWN6bnBuemV2emZlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUwMTM3ODMsImV4cCI6MjA2MDU4OTc4M30.DmCbIzVuBipwXZOGt7lqO8I9VrgBObctsrWWoBbtTiw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);